name: Pinterest Test

on:
  workflow_dispatch:
    inputs:
      search_name:
        required: true
        default: cats
      image_amount:
        required: true
        default: "20"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt update && sudo apt install -y gallery-dl

      - run: mkdir download

      - name: Download images
        run: |
          SEARCH="${{ github.event.inputs.search_name }}"
          COUNT="${{ github.event.inputs.image_amount }}"

          gallery-dl -v \
            --range 1-$COUNT \
            --http-header "User-Agent: Mozilla/5.0" \
            -D download \
            "https://www.pinterest.com/search/pins/?q=$SEARCH"

      - run: find download
